<?php

return [
    'navigation' => ['aria' => 'اداري تګ راتګ', 'dashboard' => 'ډشبورډ', 'places' => 'ځایونه', 'place_categories' => 'د ځایونو کټګورۍ', 'services' => 'خدمتونه', 'service_categories' => 'د خدمتونو کټګورۍ', 'users' => 'کارنان', 'reviews' => 'کتنې', 'contact_messages' => 'د اړیکې پیغامونه', 'place_suggestions' => 'د ځای وړاندیزونه', 'service_suggestions' => 'د خدمت وړاندیزونه', 'posts' => 'لیکنې', 'back_to_site' => 'سایټ ته بېرته', 'logout' => 'وتل', 'user_menu' => 'د کارن مینو'],
    'errors' => 'لاندې تېروتنې سمې کړئ:', 'all_rights' => 'ټول حقوق خوندي دي.', 'panel' => 'اداري پینل',
    'dashboard' => ['statistics' => 'د ډشبورډ احصایې', 'total_places' => 'ټول ځایونه', 'total_users' => 'ټول کارنان', 'total_services' => 'ټول خدمتونه', 'categories' => 'کټګورۍ', 'service_categories' => 'د خدمتونو کټګورۍ', 'reviews' => 'کتنې', 'rating' => 'درجه', 'posts' => 'لیکنې', 'contact_messages' => 'د اړیکې پیغامونه', 'pending_suggestions' => 'په تمه وړاندیزونه', 'active' => 'فعال', 'inactive' => 'غیر فعال', 'pending' => 'په تمه', 'admin' => 'مدیر', 'owner' => 'خاوند', 'published' => 'خپور شوی', 'draft' => 'مسوده', 'archived' => 'آرشیف شوی', 'places' => 'ځایونه', 'services' => 'خدمتونه', 'recent_places' => 'وروستي ځایونه', 'recent_messages' => 'وروستي د اړیکې پیغامونه', 'recent_users' => 'وروستي کارنان', 'show_all' => 'ټول ښودل', 'name' => 'نوم', 'category' => 'کټګوري', 'status' => 'حالت', 'from' => 'له', 'subject' => 'موضوع', 'email' => 'برېښنالیک', 'role' => 'رول', 'read' => 'لوستل شوی', 'unread' => 'نه دی لوستل شوی', 'empty_places' => 'تر اوسه ځای نشته', 'empty_messages' => 'تر اوسه پیغام نشته', 'empty_users' => 'تر اوسه کارن نشته'],
    'crud' => ['manage' => 'د :item مدیریت', 'all' => 'ټول :item', 'add' => 'نوی :item زیاتول', 'search' => ':item ولټوئ...', 'filter' => 'فلټر', 'clear' => 'پاکول', 'all_categories' => 'ټولې کټګورۍ', 'all_verification' => 'ټول تاییدونه', 'verified' => 'تایید شوی', 'not_verified' => 'تایید شوی نه دی', 'all_status' => 'ټول حالتونه', 'current' => 'اوسني', 'with_deleted' => 'له ړنګ شویو سره', 'deleted_only' => 'یوازې ړنګ شوي', 'address' => 'پته', 'actions' => 'کړنې', 'deleted' => 'ړنګ شوی', 'view' => 'کتل', 'edit' => 'سمول', 'restore' => 'بیا راګرځول', 'delete' => 'ړنګول', 'no_found' => ':item ونه موندل شو', 'confirm_delete' => 'ایا غواړئ دا :item ړنګ کړئ؟'],
    'contact_messages' => ['title' => 'د اړیکې پیغامونه', 'single' => 'د اړیکې پیغام', 'management' => 'د اړیکې پیغامونو مدیریت', 'details' => 'د اړیکې پیغام جزئیات', 'count' => 'د اړیکې پیغامونه (:count)', 'filter_aria' => 'د اړیکې پیغامونه فلټر کړئ', 'search_label' => 'پیغامونه ولټوئ', 'search_placeholder' => 'نوم، برېښنالیک، تلیفون یا موضوع ولټوئ...', 'status_label' => 'د حالت له مخې فلټر', 'inbox' => 'ان‌باکس', 'unread' => 'نه دی لوستل شوی', 'read' => 'لوستل شوی', 'archived' => 'آرشیف شوی', 'list_aria' => 'د اړیکې پیغامونو لړلیک', 'from' => 'له', 'subject' => 'موضوع', 'status' => 'حالت', 'received' => 'ترلاسه شوی', 'actions' => 'کړنې', 'view_from' => 'له :name څخه پیغام کتل', 'empty' => 'د اړیکې پیغام ونه موندل شو', 'pagination' => 'د اړیکې پیغامونو پاڼه‌وېش', 'back' => 'بېرته', 'name' => 'نوم', 'email' => 'برېښنالیک', 'telephone' => 'تلیفون', 'submitted_by' => 'سپارونکی', 'guest' => 'مېلمه', 'message' => 'پیغام', 'delete_confirm' => 'دا د اړیکې پیغام ړنګ شي؟'],
];
