<?php

return [
    'Badakhshan' => ['Faizabad', 'Argo', 'Baharak', 'Darayim', 'Jurm', 'Kishim', 'Raghistan', 'Shuhada', 'Tagab', 'Wakhan', 'Yawan', 'Zebak', 'Kuran wa Munjan', 'Maimay', 'Nusay', 'Shekay', 'Wurduj', 'Yamgan'],
    'Badghis' => ['Qala-e-Naw', 'Ab Kamari', 'Bala Murghab', 'Ghormach', 'Jawand', 'Muqur', 'Qadis'],
    'Baghlan' => ['Pul-e-Khumri', 'Baghlan-e-Jadid', 'Dahana-i-Ghori', 'Doshi', 'Khinjan', 'Nahrin', 'Puli Hisar', 'Andarab', 'Khost wa Fereng', 'Burka'],
    'Balkh' => ['Mazar-e-Sharif', 'Dehdadi', 'Chahar Bolak', 'Chahar Kint', 'Dawlatabad', 'Khulm', 'Sholgara', 'Shortepa', 'Zari', 'Nawbahar', 'Marmul', 'Kaldar', 'Kishindih'],
    'Bamyan' => ['Bamyan', 'Yakawlang', 'Panjab', 'Waras', 'Kahmard', 'Shibar', 'Sayghan'],
    'Daykundi' => ['Nili', 'Ashtarlay', 'Kiti', 'Miramor', 'Sangi Takht', 'Shahristan'],
    'Farah' => ['Farah', 'Anar Dara', 'Bakwa', 'Bala Buluk', 'Gulistan', 'Khak-e-Safed', 'Lash wa Juwayn', 'Pusht Rod', 'Shib Koh'],
    'Faryab' => ['Maymana', 'Almar', 'Andkhoy', 'Dawlatabad', 'Ghormach', 'Qaisar', 'Shirin Tagab', 'Pashtun Kot', 'Khani Chahar Bagh'],
    'Ghazni' => ['Ghazni', 'Andar', 'Deh Yak', 'Gelan', 'Jaghatu', 'Malistan', 'Nawa', 'Qarabagh', 'Waghaz', 'Zana Khan'],
    'Ghor' => ['Chaghcharan', 'Dawlat Yar', 'Lal wa Sarjangal', 'Pasaband', 'Shahrak', 'Taywara'],
    'Helmand' => ['Lashkar Gah', 'Gereshk', 'Kajaki', 'Musa Qala', 'Nad Ali', 'Nawa', 'Sangin', 'Marja', 'Garmser', 'Washir'],
    'Herat' => ['Herat', 'Injil', 'Guzara', 'Karukh', 'Kushk', 'Obe', 'Pashtun Zarghun', 'Zinda Jan'],
    'Jowzjan' => ['Sheberghan', 'Aqcha', 'Darzab', 'Faizabad', 'Khamyab', 'Mingajik', 'Qush Tepa'],
    'Kabul' => ['Kabul', 'Bagrami', 'Chahar Asyab', 'Deh Sabz', 'Farza', 'Guldara', 'Kalakan', 'Mir Bacha Kot', 'Paghman', 'Surobi'],
    'Kandahar' => ['Kandahar', 'Arghandab', 'Daman', 'Dand', 'Khakrez', 'Maiwand', 'Panjwai', 'Spin Boldak', 'Zheray'],
    'Kapisa' => ['Mahmud Raqi', 'Alasay', 'Hesa Awal Kohistan', 'Koh Band', 'Nijrab', 'Tagab'],
    'Khost' => ['Khost', 'Bak', 'Gurbuz', 'Mandozai', 'Musa Khel', 'Nadir Shah Kot', 'Sabari', 'Tani'],
    'Kunar' => ['Asadabad', 'Chapa Dara', 'Dangam', 'Marawara', 'Narang', 'Nari', 'Shigal'],
    'Kunduz' => ['Kunduz', 'Aliabad', 'Chahar Dara', 'Dasht-e-Archi', 'Imam Sahib', 'Khanabad', 'Qalai Zal'],
    'Laghman' => ['Mehtar Lam', 'Alingar', 'Alishing', 'Dawlat Shah', 'Qarghayi', 'Badpash'],
    'Logar' => ['Pul-e-Alam', 'Azra', 'Baraki Barak', 'Charkh', 'Kharwar', 'Mohammad Agha'],
    'Nangarhar' => ['Jalalabad', 'Achin', 'Bati Kot', 'Behsud', 'Chaparhar', 'Khogyani', 'Kuz Kunar', 'Surkh Rod'],
    'Nimruz' => ['Zaranj', 'Chakhansur', 'Kang', 'Khash Rod'],
    'Nuristan' => ['Parun', 'Bargi Matal', 'Kamdesh', 'Mandol', 'Nurgram', 'Wama', 'Waygal'],
    'Paktia' => ['Gardez', 'Ahmad Aba', 'Dand Patan', 'Jaji', 'Sayed Karam', 'Zurmat'],
    'Paktika' => ['Sharana', 'Barmal', 'Gayan', 'Mata Khan', 'Sar Hawza', 'Urgun', 'Yahya Khel'],
    'Panjshir' => ['Bazarak', 'Anaba', 'Darah', 'Khenj', 'Paryan', 'Rukha', 'Shotul'],
    'Parwan' => ['Charikar', 'Bagram', 'Ghorband', 'Jabal Saraj', 'Koh Safi', 'Salang', 'Shinwari', 'Sayed Khel'],
    'Samangan' => ['Aybak', 'Dara-i-Sufi Bala', 'Dara-i-Sufi Payin', 'Hazrat Sultan', 'Khuram wa Sarbagh', 'Ruyi Du Ab'],
    'Sar-e Pol' => ['Sar-e Pol', 'Balkhab', 'Gosfandi', 'Kohistanat', 'Sayyad', 'Sozma Qala'],
    'Takhar' => ['Taloqan', 'Baharak', 'Bangi', 'Chah Ab', 'Darqad', 'Farkhar', 'Khwaja Ghar', 'Rustaq'],
    'Urozgan' => ['Tirin Kot', 'Chora', 'Deh Rawud', 'Gizab', 'Khas Urozgan'],
    'Wardak' => ['Maidan Shar', 'Chak', 'Daymirdad', 'Jaghatu', 'Jalrez', 'Nirkh', 'Saydabad'],
    'Zabul' => ['Qalat', 'Arghandab', 'Atghar', 'Day Chopan', 'Mizan', 'Shah Joy', 'Shinkay'],
];
