<?php

return [
    'navigation' => ['aria' => 'ناوبری مدیریت', 'dashboard' => 'داشبورد', 'places' => 'مکان‌ها', 'place_categories' => 'دسته‌بندی مکان‌ها', 'services' => 'خدمات', 'service_categories' => 'دسته‌بندی خدمات', 'users' => 'کاربران', 'reviews' => 'دیدگاه‌ها', 'contact_messages' => 'پیام‌های تماس', 'place_suggestions' => 'پیشنهادهای مکان', 'service_suggestions' => 'پیشنهادهای خدمات', 'posts' => 'نوشته‌ها', 'back_to_site' => 'بازگشت به سایت', 'logout' => 'خروج', 'user_menu' => 'منوی کاربر'],
    'errors' => 'لطفاً خطاهای زیر را برطرف کنید:', 'all_rights' => 'تمام حقوق محفوظ است.', 'panel' => 'پنل مدیریت',
    'dashboard' => ['statistics' => 'آمار داشبورد', 'total_places' => 'مجموع مکان‌ها', 'total_users' => 'مجموع کاربران', 'total_services' => 'مجموع خدمات', 'categories' => 'دسته‌بندی‌ها', 'service_categories' => 'دسته‌بندی خدمات', 'reviews' => 'دیدگاه‌ها', 'rating' => 'امتیاز', 'posts' => 'نوشته‌ها', 'contact_messages' => 'پیام‌های تماس', 'pending_suggestions' => 'پیشنهادهای در انتظار', 'active' => 'فعال', 'inactive' => 'غیرفعال', 'pending' => 'در انتظار', 'admin' => 'مدیر', 'owner' => 'مالک', 'published' => 'منتشرشده', 'draft' => 'پیش‌نویس', 'archived' => 'بایگانی‌شده', 'places' => 'مکان‌ها', 'services' => 'خدمات', 'recent_places' => 'مکان‌های اخیر', 'recent_messages' => 'پیام‌های تماس اخیر', 'recent_users' => 'کاربران اخیر', 'show_all' => 'نمایش همه', 'name' => 'نام', 'category' => 'دسته‌بندی', 'status' => 'وضعیت', 'from' => 'از', 'subject' => 'موضوع', 'email' => 'ایمیل', 'role' => 'نقش', 'read' => 'خوانده‌شده', 'unread' => 'خوانده‌نشده', 'empty_places' => 'هنوز مکانی نیست', 'empty_messages' => 'هنوز پیامی نیست', 'empty_users' => 'هنوز کاربری نیست'],
    'crud' => ['manage' => 'مدیریت :item', 'all' => 'همه :item', 'add' => 'افزودن :item جدید', 'search' => 'جستجوی :item...', 'filter' => 'فیلتر', 'clear' => 'پاک کردن', 'all_categories' => 'همه دسته‌بندی‌ها', 'all_verification' => 'همه وضعیت‌های تأیید', 'verified' => 'تأییدشده', 'not_verified' => 'تأییدنشده', 'all_status' => 'همه وضعیت‌ها', 'current' => 'فعلی', 'with_deleted' => 'همراه حذف‌شده‌ها', 'deleted_only' => 'فقط حذف‌شده‌ها', 'address' => 'نشانی', 'actions' => 'عملیات', 'deleted' => 'حذف‌شده', 'view' => 'مشاهده', 'edit' => 'ویرایش', 'restore' => 'بازیابی', 'delete' => 'حذف', 'no_found' => ':itemی یافت نشد', 'confirm_delete' => 'آیا از حذف این :item مطمئن هستید؟'],
    'contact_messages' => ['title' => 'پیام‌های تماس', 'single' => 'پیام تماس', 'management' => 'مدیریت پیام‌های تماس', 'details' => 'جزئیات پیام تماس', 'count' => 'پیام‌های تماس (:count)', 'filter_aria' => 'فیلتر پیام‌های تماس', 'search_label' => 'جستجوی پیام‌ها', 'search_placeholder' => 'جستجوی نام، ایمیل، تلفن یا موضوع...', 'status_label' => 'فیلتر بر اساس وضعیت', 'inbox' => 'صندوق ورودی', 'unread' => 'خوانده‌نشده', 'read' => 'خوانده‌شده', 'archived' => 'بایگانی‌شده', 'list_aria' => 'فهرست پیام‌های تماس', 'from' => 'از', 'subject' => 'موضوع', 'status' => 'وضعیت', 'received' => 'دریافت‌شده', 'actions' => 'عملیات', 'view_from' => 'مشاهده پیام از :name', 'empty' => 'پیام تماسی یافت نشد', 'pagination' => 'صفحه‌بندی پیام‌های تماس', 'back' => 'بازگشت', 'name' => 'نام', 'email' => 'ایمیل', 'telephone' => 'تلفن', 'submitted_by' => 'ارسال‌شده توسط', 'guest' => 'مهمان', 'message' => 'پیام', 'delete_confirm' => 'این پیام تماس حذف شود؟'],
];
